//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.17 at 02:34:10 PM CET 
//


package com.dev.gis.app.xmlutils.transform.request.getCars;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{common}BookingId" minOccurs="0"/>
 *         &lt;element ref="{common}PromoCode" minOccurs="0"/>
 *         &lt;element ref="{common}CountryId" minOccurs="0"/>
 *         &lt;element ref="{common}AreaId" minOccurs="0"/>
 *         &lt;element ref="{common}CityId" minOccurs="0"/>
 *         &lt;element ref="{common}DropOffCityId" minOccurs="0"/>
 *         &lt;element ref="{common}Airport" minOccurs="0"/>
 *         &lt;element ref="{common}DropOffAirport" minOccurs="0"/>
 *         &lt;element ref="{common}ServiceCatalogId" minOccurs="0"/>
 *         &lt;element ref="{common}PickUpDate"/>
 *         &lt;element ref="{common}DropOffDate"/>
 *         &lt;element ref="{common}PickUpTime"/>
 *         &lt;element ref="{common}DropOffTime"/>
 *         &lt;element ref="{common}PickUpStationId" minOccurs="0"/>
 *         &lt;element ref="{common}DropOffStationId" minOccurs="0"/>
 *         &lt;element ref="{common}PickUpSupplierId" minOccurs="0"/>
 *         &lt;element ref="{common}DropOffSupplierId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bookingId",
    "promoCode",
    "countryId",
    "areaId",
    "cityId",
    "dropOffCityId",
    "airport",
    "dropOffAirport",
    "serviceCatalogId",
    "pickUpDate",
    "dropOffDate",
    "pickUpTime",
    "dropOffTime",
    "pickUpStationId",
    "dropOffStationId",
    "pickUpSupplierId",
    "dropOffSupplierId"
})
@XmlRootElement(name = "Travel")
public class HsgwTravel {

    @XmlElement(name = "BookingId", namespace = "common")
    protected String bookingId;
    @XmlElement(name = "PromoCode", namespace = "common")
    protected String promoCode;
    @XmlElement(name = "CountryId", namespace = "common")
    protected Integer countryId;
    @XmlElement(name = "AreaId", namespace = "common")
    protected Integer areaId;
    @XmlElement(name = "CityId", namespace = "common")
    protected Integer cityId;
    @XmlElement(name = "DropOffCityId", namespace = "common")
    protected Integer dropOffCityId;
    @XmlElement(name = "Airport", namespace = "common")
    protected String airport;
    @XmlElement(name = "DropOffAirport", namespace = "common")
    protected String dropOffAirport;
    @XmlElement(name = "ServiceCatalogId", namespace = "common")
    protected Integer serviceCatalogId;
    @XmlElement(name = "PickUpDate", namespace = "common", required = true)
    protected XMLGregorianCalendar pickUpDate;
    @XmlElement(name = "DropOffDate", namespace = "common", required = true)
    protected XMLGregorianCalendar dropOffDate;
    @XmlElement(name = "PickUpTime", namespace = "common", required = true)
    protected String pickUpTime;
    @XmlElement(name = "DropOffTime", namespace = "common", required = true)
    protected String dropOffTime;
    @XmlElement(name = "PickUpStationId", namespace = "common")
    protected Integer pickUpStationId;
    @XmlElement(name = "DropOffStationId", namespace = "common")
    protected Integer dropOffStationId;
    @XmlElement(name = "PickUpSupplierId", namespace = "common")
    protected Integer pickUpSupplierId;
    @XmlElement(name = "DropOffSupplierId", namespace = "common")
    protected Integer dropOffSupplierId;

    /**
     * Gets the value of the bookingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingId() {
        return bookingId;
    }

    /**
     * Sets the value of the bookingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingId(String value) {
        this.bookingId = value;
    }

    /**
     * Gets the value of the promoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromoCode() {
        return promoCode;
    }

    /**
     * Sets the value of the promoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromoCode(String value) {
        this.promoCode = value;
    }

    /**
     * Gets the value of the countryId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * Sets the value of the countryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCountryId(Integer value) {
        this.countryId = value;
    }

    /**
     * Gets the value of the areaId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * Sets the value of the areaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAreaId(Integer value) {
        this.areaId = value;
    }

    /**
     * Gets the value of the cityId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * Sets the value of the cityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCityId(Integer value) {
        this.cityId = value;
    }

    /**
     * Gets the value of the dropOffCityId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDropOffCityId() {
        return dropOffCityId;
    }

    /**
     * Sets the value of the dropOffCityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDropOffCityId(Integer value) {
        this.dropOffCityId = value;
    }

    /**
     * Gets the value of the airport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirport() {
        return airport;
    }

    /**
     * Sets the value of the airport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirport(String value) {
        this.airport = value;
    }

    /**
     * Gets the value of the dropOffAirport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropOffAirport() {
        return dropOffAirport;
    }

    /**
     * Sets the value of the dropOffAirport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropOffAirport(String value) {
        this.dropOffAirport = value;
    }

    /**
     * Gets the value of the serviceCatalogId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getServiceCatalogId() {
        return serviceCatalogId;
    }

    /**
     * Sets the value of the serviceCatalogId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setServiceCatalogId(Integer value) {
        this.serviceCatalogId = value;
    }

    /**
     * Gets the value of the pickUpDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPickUpDate() {
        return pickUpDate;
    }

    /**
     * Sets the value of the pickUpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPickUpDate(XMLGregorianCalendar value) {
        this.pickUpDate = value;
    }

    /**
     * Gets the value of the dropOffDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDropOffDate() {
        return dropOffDate;
    }

    /**
     * Sets the value of the dropOffDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDropOffDate(XMLGregorianCalendar value) {
        this.dropOffDate = value;
    }

    /**
     * Gets the value of the pickUpTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickUpTime() {
        return pickUpTime;
    }

    /**
     * Sets the value of the pickUpTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickUpTime(String value) {
        this.pickUpTime = value;
    }

    /**
     * Gets the value of the dropOffTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropOffTime() {
        return dropOffTime;
    }

    /**
     * Sets the value of the dropOffTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropOffTime(String value) {
        this.dropOffTime = value;
    }

    /**
     * Gets the value of the pickUpStationId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPickUpStationId() {
        return pickUpStationId;
    }

    /**
     * Sets the value of the pickUpStationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPickUpStationId(Integer value) {
        this.pickUpStationId = value;
    }

    /**
     * Gets the value of the dropOffStationId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDropOffStationId() {
        return dropOffStationId;
    }

    /**
     * Sets the value of the dropOffStationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDropOffStationId(Integer value) {
        this.dropOffStationId = value;
    }

    /**
     * Gets the value of the pickUpSupplierId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPickUpSupplierId() {
        return pickUpSupplierId;
    }

    /**
     * Sets the value of the pickUpSupplierId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPickUpSupplierId(Integer value) {
        this.pickUpSupplierId = value;
    }

    /**
     * Gets the value of the dropOffSupplierId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDropOffSupplierId() {
        return dropOffSupplierId;
    }

    /**
     * Sets the value of the dropOffSupplierId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDropOffSupplierId(Integer value) {
        this.dropOffSupplierId = value;
    }

}
