//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.18 at 03:14:57 PM MEZ 
//


package com.dev.gis.app.xmlutils.transform.request.getCars;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="3">
 *           &lt;element ref="{common}AgencyId" minOccurs="0"/>
 *           &lt;element ref="{common}AgencyNo" minOccurs="0"/>
 *           &lt;element ref="{common}TerminalId" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{common}TravelAgentBooking" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agencyIdOrAgencyNoOrTerminalId",
    "travelAgentBooking"
})
@XmlRootElement(name = "Agency")
public class HsgwAgency {

    @XmlElementRefs({
        @XmlElementRef(name = "AgencyId", namespace = "common", type = JAXBElement.class),
        @XmlElementRef(name = "AgencyNo", namespace = "common", type = JAXBElement.class),
        @XmlElementRef(name = "TerminalId", namespace = "common", type = JAXBElement.class)
    })
    protected List<JAXBElement<? extends Serializable>> agencyIdOrAgencyNoOrTerminalId;
    @XmlElement(name = "TravelAgentBooking", namespace = "common")
    protected Integer travelAgentBooking;

    /**
     * Gets the value of the agencyIdOrAgencyNoOrTerminalId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agencyIdOrAgencyNoOrTerminalId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgencyIdOrAgencyNoOrTerminalId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getAgencyIdOrAgencyNoOrTerminalId() {
        if (agencyIdOrAgencyNoOrTerminalId == null) {
            agencyIdOrAgencyNoOrTerminalId = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.agencyIdOrAgencyNoOrTerminalId;
    }

    /**
     * Gets the value of the travelAgentBooking property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTravelAgentBooking() {
        return travelAgentBooking;
    }

    /**
     * Sets the value of the travelAgentBooking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTravelAgentBooking(Integer value) {
        this.travelAgentBooking = value;
    }

}
