//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.17 at 02:34:10 PM CET 
//


package com.dev.gis.app.xmlutils.transform.request.getCars;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}RequestorName"/>
 *         &lt;element ref="{}RequestorRequestContent"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestorName",
    "requestorRequestContent"
})
@XmlRootElement(name = "RequestorRequest")
public class HsgwRequestorRequest {

    @XmlElement(name = "RequestorName", required = true)
    protected HsgwRequestorName requestorName;
    @XmlElement(name = "RequestorRequestContent", required = true)
    protected HsgwRequestorRequestContent requestorRequestContent;

    /**
     * Gets the value of the requestorName property.
     * 
     * @return
     *     possible object is
     *     {@link HsgwRequestorName }
     *     
     */
    public HsgwRequestorName getRequestorName() {
        return requestorName;
    }

    /**
     * Sets the value of the requestorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link HsgwRequestorName }
     *     
     */
    public void setRequestorName(HsgwRequestorName value) {
        this.requestorName = value;
    }

    /**
     * Gets the value of the requestorRequestContent property.
     * 
     * @return
     *     possible object is
     *     {@link HsgwRequestorRequestContent }
     *     
     */
    public HsgwRequestorRequestContent getRequestorRequestContent() {
        return requestorRequestContent;
    }

    /**
     * Sets the value of the requestorRequestContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link HsgwRequestorRequestContent }
     *     
     */
    public void setRequestorRequestContent(HsgwRequestorRequestContent value) {
        this.requestorRequestContent = value;
    }

}
