//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 04:13:03 PM CET 
//


package com.dev.http.protocoll.createEmlRequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}RequestorName"/>
 *         &lt;element ref="{}RequestorRequestContent"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestorName",
    "requestorRequestContent"
})
@XmlRootElement(name = "RequestorRequest", namespace = "")
public class RequestorRequest {

    @XmlElement(name = "RequestorName", required = true)
    protected RequestorName requestorName;
    @XmlElement(name = "RequestorRequestContent", required = true)
    protected RequestorRequestContent requestorRequestContent;

    /**
     * Gets the value of the requestorName property.
     * 
     * @return
     *     possible object is
     *     {@link RequestorName }
     *     
     */
    public RequestorName getRequestorName() {
        return requestorName;
    }

    /**
     * Sets the value of the requestorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestorName }
     *     
     */
    public void setRequestorName(RequestorName value) {
        this.requestorName = value;
    }

    /**
     * Gets the value of the requestorRequestContent property.
     * 
     * @return
     *     possible object is
     *     {@link RequestorRequestContent }
     *     
     */
    public RequestorRequestContent getRequestorRequestContent() {
        return requestorRequestContent;
    }

    /**
     * Sets the value of the requestorRequestContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestorRequestContent }
     *     
     */
    public void setRequestorRequestContent(RequestorRequestContent value) {
        this.requestorRequestContent = value;
    }

}
